# -*- coding: utf-8 -*-
# Public edition: links to the private Notion vault were removed (url=None).
"""Dataset lokasi Master Map Rhykaris — diekstrak dari Notion (Atlas, Powers & Factions, Races, Planetary Form,
Location Debt Ledger, Contradiction & Tension Log, Canon Index) pada 29 Sep 2026.
epi: 'kanon' | 'turunan' | 'inferensi' | 'terbuka'  — status KOORDINAT (bukan status keberadaan lokasi)."""
N = 'https://app.notion.com/p/'

PLACES = [
# ------------------------------------------------------------------ SINUS ADVENTUS & TITIK NOL
dict(id='litus_primum', name='Litus Primum', aka='"Pantai Pertama"', type='Landmark', cat='landmark', lat=-2.35, lon=0.0,
     epi='turunan', conf='Tinggi',
     pos='Bujur 0° = definisi meridian historis [Kanon — PF §9]. Lintang = titik pantai kepala teluk pada bujur 0° di garis pantai rekonstruksi seed 1647 [Turunan].',
     canon='Established', status='Active', hemi='Rhykar', scar='Adjacent', region='Hemisfer Rhykar — pesisir Sinus Adventus', parent='Sinus Adventus',
     strategic='Jangkar meridian 0° historis & situs ziarah identitas manusia; nilai simbolis tertinggi di seluruh geografi manusia — dan karena itu target delegitimasi alami bagi siapa pun yang menantang narasi Commonwealth.',
     notes='Titik pendaratan manusia AS 0: situs keramat sekaligus berhantu (medan pembantaian awal pendaratan berdarah). Institusi penjaga & relasi Religions [Terbuka].',
     url=None),
dict(id='dies_ignis', name='Situs Dies Ignis', type='Hidden Site', cat='hidden', lat=-1.25, lon=0.0,
     epi='turunan', conf='Sedang',
     pos='"Dasar teluk" [Kanon — PF §8]: dasar laut dangkal di depan titik pendaratan, bujur ~0°. Kedalaman di peta ≈ 75 m (air dangkal di atas kerak tipis — dua besaran berbeda).',
     canon='Established', status='Active', hemi='Rhykar', scar='Adjacent', hazards=['Magical'], region='Hemisfer Rhykar — dasar Sinus Adventus', parent='Sinus Adventus',
     strategic='Titik nol kalender manusia (AS 0) dan titik litosfer tertipis ke zona kontak — signifikansi kosmologis, historis, dan religius sekaligus; nilai strategis justru dari ketidakbolehannya disentuh.',
     notes='Salah satu kantong anomali massa = lokasi Dies Ignis [Kanon — PF §4]. Fenomena residual [Terbuka]. Contradiction #49 Resolved 29 Sep 2026 (Opsi A): "jauh dari The Scar" di Ādi Vidāra = pemisahan mekanisme (Cosmology §3), bukan jarak — situs ini tetap Adjacent (18,25° ≈ 2.640 km dari kurva).',
     url=None),
dict(id='sinus_adventus', name='Sinus Adventus', aka='Teluk Kontak · "Teluk Kedatangan"', type='Region', cat='water', lat=5.5, lon=0.0,
     epi='kanon', conf='Tinggi', label_only=True,
     pos='Sumbu teluk di bujur 0° [Kanon]. Bentuk: dangkal & lebar, mulut terbuka, sodokan tegak lurus sabuk Scar, tepi timur-laut superbenua [Kanon — PF §8]. Garis pantai = rekonstruksi seed 1647.',
     canon='Established', status='Active', access='Open', hemi='Rhykar', scar='Adjacent', region='Hemisfer Rhykar — sektor kontak', parent='Tâmtu',
     strategic='Gerbang maritim utama Rhykar↔Aëris; pelabuhan alami terbesar Rhykar; dasar teluk = titik Dies Ignis; pesisir = titik pendaratan manusia & meridian 0° historis.',
     notes='Mulut teluk = gerbang terbuka, bukan chokepoint: kendalinya ekonomi & populasi, bukan blokade. Pendaratan berdarah: teluk tidak memberi perlindungan alami.',
     url=None),
dict(id='zona_garbhen', name='Zona Garbhên', aka='zona kedalaman Dharên terdalam', type='Hidden Site', cat='hidden', lat=-3.21, lon=1.01,
     epi='turunan', conf='Sedang', proposal=True,
     pos='Garbhên "ada di sana ketika penggalian [Dies Ignis] terjadi" [Kanon — P&F Garbhên] → zona kedalaman berada di bawah sektor Sinus Adventus [Turunan]. Penanda di permukaan hanya indikasi: wilayah Dharên bersifat VERTIKAL.',
     canon='—', status='Active', hemi='Rhykar', region='Bawah tanah Ferria — di bawah sektor kontak',
     strategic='Prasasti III (zona Garbhên): satu-satunya yang menyebut perpindahan secara eksplisit; separuh informasinya tersimpan di komposisi mineral dinding — hanya terbaca sensitivitas seismik Dharên.',
     notes='Entri Atlas Draft sudah ada (01 Okt 2026). Slot Location Debt Ledger "Jaringan wilayah klan Dharên" & "Landmark era awal: situs Tiga Prasasti" masih Open. Urutan kedalaman: Guhreth → Mūlvath → Garbhên.',
     url=None),
# ------------------------------------------------------------------ HESPERIA
dict(id='hesperia', name='Hesperia', aka='"tanah bintang senja"', type='Nation', cat='region', lat=-15.5, lon=-22.5,
     epi='inferensi', conf='Sedang', label_only=True, faction='hesperia',
     pos='Relasi terkunci: pita pesisir utara Ferria di BARAT Sinus Adventus [Kanon — entri Hesperia]. Sejak v3-D, dan tetap di v4, koridor lintas-sutura (lon −159..−30) menutup pesisir utara harfiah; "pesisir utara" diwujudkan sebagai pantai selatan Mare Internum [Inferensi AI].',
     canon='Established', status='Active', access='Open', hemi='Rhykar', scar='Peripheral', pop='Large', region='Hemisfer Rhykar — koridor pesisir barat', parent='Ferria',
     strategic='Heartland manusia & kursi paramount Commonwealth; basis agraris utama Ferria; asal-usul standar moneter Fides; militer terbesar planet bermarkas di sini.',
     notes='Etimologi "menghadap barat" = fosil arah ekspansi dari teluk pendaratan. Pita pesisir moderat = tanah Satvan paling berharga sebelum AS 0 (Central Tension #4). Tetangga: Foedera (marka timur), Interregna (koridor tengah).',
     url=None),
dict(id='aurelia', name='Aurelia', type='City', cat='capital', lat=-5.49, lon=-8.31,
     epi='inferensi', conf='Sedang', faction='hesperia',
     pos='Syarat kanon: bujur negatif; ≠ titik pendaratan; "tempat lebih produktif & terpertahankan" [PF §8]; Peripheral. Dipilih di sungai utama yang bermuara di pesisir barat-daya teluk, ~360 km hulu dari Portus (analog Roma–Ostia) [Inferensi AI].',
     canon='Established', status='Active', access='Open', hemi='Rhykar', scar='Peripheral', pop='Megacity', region='Hemisfer Rhykar — koridor pesisir barat', parent='Hesperia',
     strategic='Kursi paramount Commonwealth; titik acuan meridian resmi planet; pusat definisi standar Fides; markas Senat, Imperator, dan komando militer terbesar Rhykaris.',
     notes='MERIDIAN RESMI melewati kota ini: di peta ini ≈ 8,31° barat dari meridian historis (≈ 1.200 km) — jarak antara "kedatangan" dan "kekuasaan". Kandidat pasangan pelabuhan: Portus.',
     url=None),
dict(id='portus', name='Portus', aka='nama kandidat (analog Ostia)', type='City', cat='port', lat=-3.03, lon=-7.60,
     epi='inferensi', conf='Sedang', proposal=True, faction='hesperia',
     pos='Kandidat ledger: "pesisir barat teluk (sisi Hesperia)". Ditempatkan di muara sungai Aurelia, di sambungan Mare Internum–teluk [Inferensi AI].',
     canon='—', status='Active', hemi='Rhykar', region='Hemisfer Rhykar — pesisir barat-daya Sinus Adventus',
     strategic='Pelabuhan utama Sinus Adventus & gerbang laut Aurelia; mengawasi sambungan Mare Internum ↔ teluk.',
     notes='Slot Location Debt Ledger "Portus — kota pelabuhan utama Sinus Adventus" masih OPEN (Kecil — Pilih Kandidat). Butuh ketok.',
     url=None),
# ------------------------------------------------------------------ KORIDOR TENGAH
dict(id='interregna', name='Interregna', aka='d/h Regna Media', type='Region', cat='region', lat=-18.0, lon=-1.5,
     epi='inferensi', conf='Sedang', label_only=True,
     pos='Relasi terkunci: koridor tengah Ferria di antara Hesperia (barat) dan Foedera (timur/tenggara teluk) [Kanon]. Di peta: daratan selatan kepala teluk. Jumlah kerajaan = ilustratif (knob terbuka).',
     canon='Established', status='Active', hemi='Rhykar', scar='Peripheral', pop='Large', region='Hemisfer Rhykar — koridor tengah', parent='Ferria',
     strategic='Medan perebutan utama papan politik AS 1647; jahitan zona moneter Fides↔Pactum; ruang manuver terakhir bagi polity yang menolak memilih payung.',
     notes='"Interregnum selalu berakhir" — klaim temporal kartografi Hesperia. Terjepit tiga arah: kampanye Florian (timur), klaim Anabasim (arah Scar), gravitasi moneter Hesperia (barat). Kanon: "belasan kedaulatan terpisah".',
     url=None),
dict(id='aventalia', name='Aventalia', type='Nation', cat='kingdom', lat=-12.5, lon=-7.5,
     epi='inferensi', conf='Sedang', faction='aventalia',
     pos='Urutan relatif terkunci: segmen paling BARAT koridor, dekat sfera Hesperia [Kanon — entri]. Koordinat presisi [Inferensi AI].',
     canon='Draft', status='Active', access='Open', hemi='Rhykar', scar='Peripheral', pop='Medium', hazards=['Political'], region='Interregna — koridor tengah (kerajaan belum tersentuh, front terjauh)', parent='Interregna',
     strategic='Belum jadi target aktif kampanye — tapi posisinya di ujung barat berarti jatuhnya (kelak) yang akan pertama kali memaksa reaksi langsung Hesperia. Untuk sekarang: representasi tipologi "masih merasa punya waktu".',
     notes='Endonim Communis dialek vassal: aventus (adventus tererosi) + -alia — "tanah yang menanti". Ironi optimisme temporal.',
     url=None),
dict(id='tarvenna', name='Tarvenna', type='Nation', cat='kingdom', lat=-13.5, lon=-1.8,
     epi='inferensi', conf='Sedang', faction='tarvenna',
     pos='Urutan relatif terkunci: segmen TENGAH, di jalur kampanye setelah Cassivalla [Kanon — entri]. Koordinat presisi [Inferensi AI].',
     canon='Draft', status='Contested', access='Restricted', hemi='Rhykar', scar='Peripheral', pop='Medium', hazards=['Political', 'Warfare'], region='Interregna — koridor tengah (kerajaan panggung Arc 1)', parent='Interregna',
     strategic='Simpul perlintasan koridor tengah (jalur darat/dagang) — kontrolnya menentukan tempo aneksasi lebih jauh ke barat. Satu-satunya kerajaan Interregna yang pernah berupaya merintis liga pertahanan kolektif.',
     notes='Endonim: tar- + venna (venia) — "tempat yang meminta kerelaan". Kini ironis: dipaksa "meminta izin" pada Florian. Status AS 1647: Contested.',
     url=None),
dict(id='cassivalla', name='Cassivalla', aka='Provincia Cassivallae', type='Nation', cat='ruin', lat=-14.6, lon=5.0,
     epi='inferensi', conf='Sedang', faction='cassivalla',
     pos='Urutan relatif terkunci: segmen paling TIMUR (paling dekat sfera Foedera), ditelan pertama ~AS 1630-an [Kanon — entri]. Koordinat presisi [Inferensi AI].',
     canon='Draft', status='Destroyed', access='Restricted', hemi='Rhykar', scar='Peripheral', pop='Sparse', hazards=['Political', 'Warfare'], region='Interregna — koridor tengah (kerajaan jatuh, fase awal aneksasi)', parent='Interregna',
     strategic='Bekas benteng simpul koridor tengah — nilai logistiknya (kontrol tempo aneksasi ke barat) adalah alasan Florian memilih menyerangnya lebih dulu, bukan sentimen.',
     notes='cassus + valla — "benteng yang kosong/gagal". Eksonim administratif Foedera pasca-jatuh: "Provincia Cassivallae". Controlling: Foedera + Interregna.',
     url=None),
dict(id='nundina', name='Nundina', type='City', cat='city', lat=-9.80, lon=1.19,
     epi='inferensi', conf='Sedang', faction='nundina',
     pos='Relasi: kota merdeka di koridor tengah (jahitan Fides↔Pactum); "beberapa hari jalan kaki" dari Silva Nullius [Kanon]. Ditempatkan di tepi sungai di barat Silva Nullius [Inferensi AI].',
     canon='Established', status='Active', access='Open', hemi='Rhykar', scar='Peripheral', pop='Large', hazards=['Political'], region='Hemisfer Rhykar — koridor tengah, jahitan moneter', parent='Interregna',
     strategic='Pasar spot terbesar koridor (jahitan Fides↔Pactum); preseden hukum union & adopsi lintas-ras; simpul perantara dagang-diplomasi informal lintas-ras; kandidat setting Arc 1 web novel.',
     notes='Controlling Factions SENGAJA kosong: kota merdeka; Omneris berkuasa de facto tanpa kursi formal. Setting utama Fase 2–3 Arc 1. Posisi dalam urutan target Florian = knob.',
     url=None),
dict(id='silva_nullius', name='Silva Nullius', type='Region', cat='forest', lat=-11.3, lon=3.1,
     epi='inferensi', conf='Sedang', label_only=True,
     pos='Relasi: sabuk hutan di jahitan yurisdiksi Foedera ↔ jalur dagang koridor tengah; 2–3 minggu jalan kaki dari Sharanya; beberapa hari dari Nundina [Kanon]. Di peta: ≈270 km dari Sharanya, ≈140 km dari Nundina [Inferensi AI].',
     canon='Established', status='Active', access='Remote', hemi='Rhykar', scar='Peripheral', climate='Temperate', hazards=['Ecological', 'Criminal', 'Political'], region='Hemisfer Rhykar — koridor tengah, sabuk hutan tak berpemilik', parent='Interregna',
     strategic='Panggung Fase 1 SoR:D (kedatangan Sulis, lima tahap kepercayaan, sapuan pelacak). Jalur tikus lintas-yurisdiksi Foedera↔Interregna; radius operasi jaringan kurir Satvan Perbatasan.',
     notes='Preseden: dasar Zona I + tepi luar jangkauan semai Zona V (bukan zona ketujuh). GARAM = satu-satunya kebutuhan yang mustahil dipenuhi dari dalam hutan.',
     url=None),
dict(id='kloaka', name='Kloaka', type='Kingdom (P&F)', cat='kingdom', lat=-3.8, lon=-4.3,
     epi='inferensi', conf='Rendah', proposal=True, faction='kloaka',
     pos='Ledger: "Kloaka kandidat kuat bawah-Aurelia [belum diverifikasi]". Dibaca sebagai dataran rendah hilir Aurelia — pesisir berawa selatan teluk antara Portus dan Litus Primum, terjangkau penyelundupan laut Peratēs [Inferensi AI — Rendah].',
     canon='Established (P&F)', status='Fractured', hemi='Rhykar', region='Pesisir selatan Sinus Adventus (usulan)',
     strategic='Zona tanpa hukum: badge Omneris tidak diakui, dokumen Venditarii tak perlu diverifikasi, kontrak Chrematia tanpa penegakan. Ruang fisik pasar gelap — "cuma satu dari tiga kaki yang tidak punya siapa-siapa untuk dituntut".',
     notes='Raja nominal masih bertakhta; penegakan hukum yang absen. Faction Type "Kingdom" sengaja dipertahankan (ironis, bukan cacat). Slot HQ faksi tertutup masih OPEN — butuh ketok.',
     url=None),
# ------------------------------------------------------------------ FOEDERA & FRONTIER TIMUR
dict(id='foedera', name='Foedera', type='Nation', cat='region', lat=-4.0, lon=17.5,
     epi='inferensi', conf='Sedang', label_only=True, faction='foedera',
     pos='Relasi terkunci: marka timur Ferria — sektor timur/tenggara Sinus Adventus, frontier menghadap sabuk Scar [Kanon — entri]. Batas barat bergerak (Tension #19) — digambar snapshot AS 1647 [Inferensi AI].',
     canon='Established', status='Active', access='Open', hemi='Rhykar', scar='Adjacent', pop='Large', hazards=['Warfare', 'Political'], region='Hemisfer Rhykar — marka timur / frontier Scar', parent='Ferria',
     strategic='Frontier satu-satunya penyangga antara ekspansi Anabasim dan koridor manusia; markas Ordo Foederis dengan akses Sistem II-B; proto-imperium yang menantang Hesperia dari luar payung; pusat zona standar Pactum.',
     notes='Berdiri AS 1435 ketika garis militer Ordo Foederis memformalkan provinsi terjauh jadi kerajaan. Ironi geografis: frontier timur = wilayah Satvan yang erosinya paling segar.',
     url=None),
dict(id='synodia', name='Synodia', type='City', cat='capital', lat=3.03, lon=25.53,
     epi='inferensi', conf='Sedang', faction='foedera',
     pos='Relasi: kursi dinasti Palladis, fortress city penyangga frontier Scar (Adjacent) [Kanon]. Ditempatkan di tepi sungai timur danau besar Foedera, ≈10° dari kurva [Inferensi AI].',
     canon='Established', status='Active', access='Open', hemi='Rhykar', scar='Adjacent', pop='Large', region='Hemisfer Rhykar — marka timur / frontier Scar', parent='Foedera',
     strategic='Kursi dinasti Palladis & dewan multi-ras; pusat komando ekspansi Florian; jangkar zona Pactum; fortress city penyangga frontier Scar.',
     notes='Nama dari Yun. synodos via register Hellenika — diferensiasi register dari Latin dinasti Hesperia adalah fitur politik. Markas Ordo Foederis: Synodia vs garnisun frontier = knob.',
     url=None),
dict(id='sharanya', name='Sharanya', type='Town', cat='town', lat=-8.13, lon=5.05,
     epi='inferensi', conf='Sedang', faction='foedera',
     pos='Relasi: marka BARAT Foedera, lembah sungai tempat administrasi menipis ke arah Interregna; titik nol rute Arc 1 Sharanya → Silva Nullius → Nundina [Kanon]. Ditempatkan di lembah sungai [Inferensi AI].',
     canon='Established', status='Active', access='Restricted', hemi='Rhykar', scar='Peripheral', climate='Continental', pop='Small', hazards=['Political', 'Warfare'], region='Hemisfer Rhykar — marka barat Foedera', parent='Foedera',
     strategic='Sumber terkunci pipa veteran Auxilia ke kota-kota koridor; komunitas asal Kuhsa, Mrigan, dan Satdhar. Contoh kerja posisi komunitas Urdhai (1)+(3): berkewarganegaraan DAN tahu-lalu-memilih-diam.',
     notes='Native range Urdhai. Prinsip pemisah: NORMA universal, WUJUD lokal — Diam yang Dipilih diajarkan dalam wujud tempat ini.',
     url=None),
dict(id='liminara', name='Liminara', type='Kingdom (P&F)', cat='fortress', lat=-3.0, lon=37.5,
     epi='inferensi', conf='Rendah', proposal=True, faction='liminara',
     pos='Kanon: kerajaan benteng-medan yang "paling langsung terancam ekspansi Anabasim", flora gunung, pembeli besi Ktonia. Ditempatkan di pegunungan tanjung timur-laut Ferria, bersebelahan dengan busur Lereng Timur [Inferensi AI — Rendah].',
     canon='Established (P&F)', status='Active', hemi='Rhykar', region='Tanjung timur-laut Ferria (usulan)',
     strategic='Terrain (satu-satunya layer yang sepenuhnya milik mereka) + manufaktur senjata dari besi Ktonia + flora gunung → obat ber-densitas-nilai-tinggi.',
     notes='Entri Atlas Draft sudah ada (01 Okt 2026); slot HQ faksi tertutup tetap OPEN. Posisi terhadap Anabasim: ancaman untuk diblok atau leverage untuk dinegosiasi?',
     url=None),
dict(id='castra_birath', name='Castra Birath', aka='eksonim intel Commonwealth/Foedera', type='Hidden Site', cat='zone', lat=5.4, lon=31.5,
     epi='terbuka', conf=None, zone_r=3.2, faction='anabasim',
     pos='SENGAJA TIDAK DIKUNCI [Kanon — entri: "Posisi persis dalam busur Terbuka — sengaja: Foedera pun tidak tahu"]. Digambar sebagai ZONA ketidakpastian di daratan pita Lereng Timur, bukan titik.',
     canon='Draft', status='Active', access='Hidden', hemi='Pre-Merger Unknown', scar='Within Scar', pop='Small', hazards=['Political', 'Magical', 'Ecological'], region='Latus Orientale — kantong stabil inti', parent='Latus Orientale',
     strategic='Jantung konsolidasi: kedudukan komunitas pendiri Birath & pusat gravitasi kepemimpinan Anabasim. Bukan ibukota — ini tempat otoritas-lewat-kapasitas berdomisili.',
     notes='Nama Birath untuk situsnya sendiri sengaja belum stabil — fiksasinya adalah peristiwa politik yang belum terjadi (plot seed). Tumpang tindih dengan habitat cognitive-class monsters (Tension #20).',
     url=None),
dict(id='vasundha', name='Vasundha', type='Tribe (P&F)', cat='tribe', lat=-25.0, lon=26.0,
     epi='inferensi', conf='Rendah', proposal=True, faction='vasundha',
     pos='Kanon: Satvan pedalaman yang menolak aliansi Anabasim; posisi relatif terhadap Foedera = knob entri Foedera. Ditempatkan di pedalaman selatan Foedera — "interior yang tidak diminati manusia" [Inferensi AI — Rendah].',
     canon='Established (P&F)', status='Active', hemi='Rhykar', region='Pedalaman Ferria selatan Foedera (usulan)',
     strategic='Pengetahuan medan yang sangat dalam; kekuatan yang tidak portabel — hanya eksis selama mereka masih di tanah itu.',
     notes='Slot ledger "Teritori Satvan: Pedalaman, Frontier Konsolidasi, + posisi Vasundha" masih OPEN.',
     url=None),
# ------------------------------------------------------------------ PEDALAMAN FERRIA
dict(id='ferria', name='Ferria', aka='Mahādhara (Dharên) · Satvabhūmi (Satvan)', type='Continent', cat='continent', lat=-38.0, lon=-40.0,
     epi='kanon', conf='Tinggi', label_only=True,
     pos='Superbenua tunggal, geser barat, menjulur ke kutub S, laut di sisi antimeridian, lintas-sutura via satu koridor [Kanon — PF §5, CI #110]. Garis pantai = rekonstruksi seed 1647.',
     canon='Established', status='Active', hemi='Rhykar', region='Hemisfer Rhykar', parent='Rhykaris',
     strategic='Satu-satunya superbenua planet (23% permukaan). Rumah Dharên, Satvan, Urdhai, dan seluruh peradaban manusia sejak AS 0.',
     notes='Tiga zona iklim dalam satu benua: pesisir utara moderat → interior kering swing-ekstrem → ujung selatan beku. Peta manusia menghapus endonim Dharên & Satvan (Central Tension #4).',
     url=None),
dict(id='fons_secundus', name='Fons Secundus', type='Town', cat='oasis', lat=-22.0, lon=-19.0,
     epi='inferensi', conf='Sedang',
     pos='Relasi: interior Ferria, pedalaman barat-daya Sinus Adventus, di atas kantong anomali massa kedua [Kanon relasional + Inferensi AI Sedang]. Di peta ≈36° dari kurva → Unaffected (cocok field).',
     canon='Draft', status='Active', access='Remote', hemi='Rhykar', scar='Unaffected', climate='Arid', pop='Small', hazards=['Climate', 'Political'], region='Interior Ferria — zona kering swing-ekstrem', parent='Ferria',
     strategic='Titik masuk paradigma medis Charité ke Rhykaris — hulu silsilah pengetahuan yang berujung xenograft (Theoria–Pharmakeia). Air anomali di interior kering = nilai survival permanen.',
     notes='Rongga ringan Aëris DI BAWAH litosfer Rhykar = identitas situs. Korelasi aurora↔kantong anomali = Tension #21 (Intentionally Deferred) — jangan dipakai sebagai fakta.',
     url=None),
dict(id='ktonia', name='Ktonia', type='Kingdom (P&F)', cat='mine', lat=-4.39, lon=39.90,
     epi='inferensi', conf='Rendah', proposal=True, faction='ktonia',
     pos='Kanon: satu-satunya deposit logam iridescent = "kantong dominan-substansi di kedalaman" (P&F), "ditambang dari zona yang bersinggungan dengan The Scar" (Ecology §3). Ditempatkan di massif timur-dalam Ferria, di pedalaman Liminara (≈400 km), 12,3° dari kurva → Adjacent [Inferensi AI — Sedang]; titik tepat di dalam massif [Inferensi AI — Rendah].',
     canon='Established (P&F)', status='Active', hemi='Rhykar', region='Massif timur Ferria (usulan)',
     strategic='Monopoli berlapis: logam umum (bisa disubstitusi) + iridescent (tidak tergantikan; memutus proyeksi Sistem II-B). "Main dua sisi diam-diam" antara Hesperia dan Foedera.',
     notes='Kenapa belum direbut: laju ekstraksi iridescent geologis, bukan politis — tidak ada hadiah instan bagi perebut. Iridescent ≠ Crystallum Fissurae (dua ujung satu variabel). Titik peta direlokasi dari Altiplano (−45,0/−12,0) karena 8.715 km dari Liminara (≈6,7× keliling planet setara laut) dan bertentangan dengan Ecology §3 (ketok A, 01 Okt).',
     url=None),
dict(id='vastitas', name='Vastitas', type='Region', cat='region', lat=-78.0, lon=-30.0,
     epi='kanon', conf='Tinggi', label_only=True,
     pos='Latitude −90 = kutub selatan di dalam region ini [Kanon]. Cold desert = daratan, ujung selatan superbenua [Kanon — PF §5.0].',
     canon='Established', status='Active', access='Remote', hemi='Rhykar', scar='Unaffected', climate='Polar', hazards=['Climate'], region='Hemisfer Rhykar — ujung selatan', parent='Ferria',
     strategic='Bioma paling tidak ramah di planet. Kandidat kanon untuk lokasi terisolasi ekstrem: penjara alami, situs rahasia, habitat hiper-teradaptasi.',
     notes='Batu telanjang beku — tidak ada air untuk dibekukan. Endonim Dharên/Satvan [Terbuka].',
     url=None),
# ------------------------------------------------------------------ THE SCAR
dict(id='the_scar', name='The Scar', aka='Cicatrix', type='Region', cat='scar', lat=-21.4, lon=90.0,
     epi='kanon', conf='Tinggi', label_only=True,
     pos='Small circle pusat −55,5°/0°, radius 72,5° [Kanon — PF §3]; lebar pita 13,0° (Tension #18 Resolved). Overlay terukur di peta ini 3,99%; lebar turunan untuk 4,000% = 13,03°.',
     canon='Established', status='Active', access='Unstable', hemi='Pre-Merger Unknown', scar='Within Scar', hazards=['Magical', 'Ecological', 'Climate'], region='Sabuk sutura global', parent='Rhykaris',
     strategic='Kristal magis terpekat & paling tidak stabil di planet; satu-satunya wilayah yang tidak bisa diklaim; tanah kelahiran Birath; jalur wajib kontak Rhykar↔Aëris.',
     notes='Tidak bisa diklaim — bukan karena perjanjian, tapi karena mendahului konsep kepemilikan tanah. Ketiga Register aktif di intensitas maksimum; kompas tidak bisa dipercaya.',
     url=None),
dict(id='culmen', name='Culmen Cicatricis', aka='busur Puncak', type='Region', cat='arc', lat=21.0, lon=-9.0,
     epi='turunan', conf='Sedang', label_only=True,
     pos='Busur di sekitar puncak +17° / bujur 0° [Kanon]. Batas busur di peta: azimut −25°..+25° dari pusat cap (≈ lon −24°..+24°) [Inferensi AI].',
     canon='Draft', status='Active', access='Unstable', hemi='Pre-Merger Unknown', scar='Within Scar', climate='Temperate', region='Sabuk sutura global — busur Puncak', parent='The Scar',
     strategic='Gerbang utama Rhykar↔Aëris: berhadapan langsung dengan Sinus Adventus & titik Dies Ignis. Bahu timur busur = rute Penyeberangan The Scar bersejarah.',
     notes='Ekspresi dominan benua×laut — TERKONFIRMASI di peta rekonstruksi: pesisir Ferria + laut Aëris. "Simpul netral tipe Emporys hidup dari status tak-terklaim ini."',
     url=None),
dict(id='latus_occidentale', name='Latus Occidentale', aka='busur Lereng Barat · Pegunungan Sutura', type='Region', cat='arc', lat=-25.6, lon=-96.3,
     epi='turunan', conf='Sedang', label_only=True,
     pos='Busur lereng barat [Kanon]. Batas di peta: azimut −135°..−25° (bujur ≈ −120°..−25°) [Inferensi AI]. Bagian azimut −135°..−31° berada di dalam koridor las benua×benua (dikunci v3-D, dipertahankan v4; azimut −166°..−31°, bujur −159°..−30°); 6° paling timur sudah selat.',
     canon='Draft', status='Active', access='Unstable', hemi='Pre-Merger Unknown', scar='Within Scar', climate='Continental', hazards=['Magical', 'Ecological', 'Climate'], region='Sabuk sutura global — busur Lereng Barat', parent='The Scar',
     strategic='Barrier alami tertinggi sepanjang sabuk — nilai strategisnya justru impermeabilitas. Sekaligus satu-satunya jalur darat lintas-hemisfer (Change Log #6): menembus sabuk terdeformasi, teritori Birath.',
     notes='Ekspresi benua×benua TERKONFIRMASI (koridor darat v4), tetapi pasangannya bukan daratan sedang Aëris melainkan porsi lintas-sutura superbenua. Komunitas Birath yang belum bergabung karena jarak.',
     url=None),
dict(id='latus_orientale', name='Latus Orientale', aka='busur Lereng Timur', type='Region', cat='arc', lat=-4.5, lon=66.0,
     epi='turunan', conf='Sedang', label_only=True,
     pos='Busur lereng timur [Kanon]. Batas di peta: azimut +25°..+135° [Inferensi AI].',
     canon='Draft', status='Contested', access='Unstable', hemi='Pre-Merger Unknown', scar='Within Scar', climate='Temperate', hazards=['Magical', 'Ecological', 'Climate', 'Warfare', 'Political'], region='Sabuk sutura global — busur Lereng Timur', parent='The Scar',
     strategic='Busur frontier: menghadap marka timur — arc Foedera–Anabasim. Alamat situs konsolidasi Birath. Papan catur ekspansi Fase 1 Anabasim.',
     notes='Ekspresi benua-menipis×laut TERKONFIRMASI (pesisir timur-laut Ferria) + tambahan: pinggir selatan Šadûmāt di sisi Aëris — arah Fase lanjutan Anabasim ("mengarah ke sisi hemisfer Aëris").',
     url=None),
dict(id='ima', name='Ima Cicatricis', aka='busur Palung', type='Region', cat='arc', lat=-49.0, lon=165.0,
     epi='turunan', conf='Sedang', label_only=True,
     pos='Busur palung sekitar antimeridian, lintang ~−52° [Kanon]. Batas di peta: |azimut| > 135° [Inferensi AI].',
     canon='Draft', status='Active', access='Remote', hemi='Pre-Merger Unknown', scar='Within Scar', hazards=['Magical', 'Ecological', 'Climate'], region='Sabuk sutura global — busur Palung', parent='The Scar',
     strategic='Nilai strategisnya adalah ketidakhadiran: segmen paling tidak terjamah, tidak terpetakan, tidak diperebutkan. Blank spot yang disengaja.',
     notes='Laut×laut dominan (2/3 busur); sepertiga barat (lon −159..−120) tertimpa ujung barat koridor las — FRIKSI kecil dengan batas busur.',
     url=None),
# ------------------------------------------------------------------ AËRIS
dict(id='ellumat', name='Ellumāt', aka='"Tanah yang Terangkat"', type='Continent', cat='continent', lat=62.0, lon=176.0,
     epi='kanon', conf='Tinggi', label_only=True,
     pos='Jantung Aëris di antipode pusat Rhykar (+55,5°, 180°), ~3,5% permukaan [Kanon — CI #110]. Garis pantai = rekonstruksi.',
     canon='Established', status='Active', hemi='Aëris', region='Hemisfer Aëris', parent='Rhykaris',
     strategic='Benua utama hemisfer Aëris; jantung peradaban Elvari dan pusat sistem kasta Iluhar→Napûm.',
     notes='Mandala Kemurnian 4 ring: tanpa garis batas, hanya pancaran yang menipis — ditegakkan drift biologis, bukan patroli. Peta Elvari & peta Commonwealth tidak bisa saling diterjemahkan.',
     url=None),
dict(id='libbal', name='Libbāl', type='City', cat='capital', lat=55.5, lon=180.0,
     epi='turunan', conf='Tinggi',
     pos='"Interior tinggi, titik terjauh dari kurva Scar" [Kanon — Mandala] → titik terjauh dari small circle = antipode pusat cap: (+55,5°, 180°), 107,5° dari kurva [Turunan geometris].',
     canon='Established', status='Active', access='Remote', hemi='Aëris', scar='Unaffected', pop='Large', region='Hemisfer Aëris — Ring 0 mandala Elvari', parent='Ellumāt',
     strategic='Jangkar meridian Elvari; kursi Sarum & kuil Lex Aēlis; arsip standar peradaban yang kerangkanya dipakai institusi se-Rhykaris tanpa sadar. Kota yang tidak menguasai apa-apa secara formal — dan karena itu tidak bisa diserang secara formal.',
     notes='MERIDIAN ELVARI = antimeridian manusia: nol-nya Elvari adalah 180°-nya manusia. Controlling Factions SENGAJA kosong (Iluhar tanpa alamat).',
     url=None),
dict(id='zona_ambang', name='Zona Ambang Ellumāt', aka='label kerja', type='Region', cat='region', lat=51.5, lon=146.0,
     epi='inferensi', conf='Sedang', label_only=True, faction='andura',
     pos='Relasi: Ring 3 — tepi Ellumāt yang menghadap Scar & pesisir kontak; ujung rute Penyeberangan [Kanon]. Di peta: pesisir barat-daya Ellumāt, ≈87° dari kurva [Inferensi AI]; #210 menyebut tepi Ellumāt terdekat ke kurva (≥73,5°) sebagai posisi paling pas — diputuskan di Tension #17.',
     canon='Established', status='Active', hemi='Aëris', scar='Unaffected', pop='Medium', region='Hemisfer Aëris — Ring 3 mandala (zona ambang)', parent='Ellumāt',
     strategic='Tempat sistem kasta Elvari memproduksi oposisinya sendiri; persilangan kontak manusia–Tehari–Napûm; rumah Napûm Berteritori.',
     notes='DITUTUP 29 Sep 2026 (Canon Index #210): Scar Proximity = Unaffected — seluruh Ellumāt ≥73,5° dari kurva. Kontras yang dibaca Napûm Berteritori datang dari kantong anomali massa #3 di bawah zona ini (bongkahan litosfer Rhykar / Substansi I), bukan dari sabuk.',
     url=None),
dict(id='gerbang_r2', name='Gerbang Diplomatik Ring 2', aka='belum bernama', type='Usulan', cat='gate', lat=48.5, lon=160.0,
     epi='inferensi', conf='Rendah', proposal=True,
     pos='Kanon: "gerbang diplomatik manusia (Ring 2) = ujung rute Penyeberangan" — entri gerbang [Terbuka]. Pelabuhan Ring 2 (~14° dari Libbāl) di pesisir selatan [Inferensi AI].',
     canon='—', status='Active', hemi='Aëris', region='Ellumāt — Ring 2 (lingkar dagang & pesisir)',
     strategic='Titik tempat standar Elvari melonggar cukup jauh untuk menerima manusia — dan cukup dekat untuk memastikan manusia tahu mereka sedang diterima.',
     notes='Entri Atlas Draft sudah ada (01 Okt 2026). Pelabuhan Marum Ring 2 juga "entri menyusul".', url=None),
dict(id='sadumat', name='Šadûmāt', aka='"Tanah Gunung" — eksonim Elvari', type='Continent', cat='continent', lat=31.0, lon=78.0,
     epi='turunan', conf='Sedang', label_only=True,
     pos='Daratan sedang sekunder dekat Scar ~lat 16°/lon 60° (sesi Master Map 11 Jul, belum diformalkan di Atlas) [Turunan]. Lebih kecil dari Ellumāt, topografi tinggi dominan [Kanon — entri].',
     canon='Established', status='Active', hemi='Aëris', region='Hemisfer Aëris', parent='Rhykaris',
     strategic='Daratan tinggi jangkar populasi Vayuri; nilai strategisnya naik di AS 1647 seiring perburuan organ atmosferik Vayuri oleh jaringan perdagangan budak.',
     notes='Endonim Vayuri berupa frasa-lagu yang sengaja tidak difiksasi tertulis. Dominasi Elvari berhenti di garis pantai; di ketinggian Šadûmāt standar Iluhar tidak berlaku.',
     url=None),
dict(id='peg_sadumat', name='Pegunungan Šadûmāt', type='Region', cat='mountain', lat=15.6, lon=69.0,
     epi='inferensi', conf='Sedang', label_only=True,
     pos='Massif tinggi lobus timur Šadûmāt (puncak ≈5.000+ m di peta). Massif-nya = relief lapisan fisik Master Map v4 [Turunan]; penempatan entri Atlas di massif ini [Inferensi AI].',
     canon='Established', status='Active', access='Remote', hemi='Aëris', region='Hemisfer Aëris — dataran tinggi Šadûmāt', parent='Šadûmāt',
     strategic='Jangkar populasi Vayuri Pegunungan; sumber organ atmosferik yang diburu jaringan perdagangan budak AS 1647; zona di luar jangkauan efektif standar Iluhar.',
     notes='Nama final [Terbuka — non-blocking].', url=None),
dict(id='sabuk_pohon', name='Sabuk Pohon Raksasa Šadûmāt', type='Region', cat='forest', lat=20.0, lon=51.0,
     epi='inferensi', conf='Sedang', label_only=True,
     pos='Lereng barat-daya Šadûmāt yang menghadap koridor angin — curah tertinggi di peta. Bioma megaflora & curahnya = lapisan fisik Master Map v4 [Turunan]; penempatan entri Atlas di sabuk ini [Inferensi AI].',
     canon='Established', status='Active', access='Remote', hemi='Aëris', region='Hemisfer Aëris — sabuk megaflora Šadûmāt', parent='Šadûmāt',
     strategic='Hunian kanopi Vayuri Pohon Raksasa; megaflora = sumber material & farmakologi unik Aëris.',
     notes='[Terbuka] perluasan sabuk megaflora ke Ellumāt.', url=None),
dict(id='nagu', name='Nagû', aka='"wilayah seberang laut"', type='Region', cat='islands', lat=38.5, lon=-12.0,
     epi='inferensi', conf='Sedang', label_only=True,
     pos='Kanon: kepulauan mengelompok di jalur koridor angin, bukan taburan merata. Posisi koridor = Tension #16 (Deferred). Di peta: gugus utama di utara Culmen + rantai timur menuju Ellumāt [Inferensi AI].',
     canon='Established', status='Active', access='Open', hemi='Aëris', region='Hemisfer Aëris — gugus kepulauan', parent='Tâmtu',
     strategic='Gugus kepulauan di jalur koridor angin = simpul alami pelayaran, perdagangan, dan komunitas pesisir. Arena operasi Peratēs, kandidat lokasi simpul pasar, wilayah Tehari Pesisir.',
     notes='Penamaan per gugus berlapis: nama Elvari di peta, nama Tehari di air, nama pelaut manusia di log pelabuhan.',
     url=None),
dict(id='tamtu', name='Tâmtu', aka='samudra global', type='Body of Water', cat='water', lat=44.0, lon=-95.0,
     epi='kanon', conf='Tinggi', label_only=True,
     pos='62% permukaan planet [Kanon — PF §5 revisi]. Terukur di peta: 62,000%.',
     canon='Established', status='Active', hemi='Aëris', region='Samudra global', parent='Rhykaris',
     strategic='62% permukaan planet. Seluruh jalur laut utama, jasa pelayaran Peratēs, dan simpul pasar maritim beroperasi di atasnya; komunitas Tehari hidup di dalamnya.',
     notes='Akkadia tâmtu/tiāmtum. [Terbuka] relasi tâmtu↔tehom.', url=None),
dict(id='corona_glacialis', name='Corona Glacialis', aka='"mahkota putih"', type='Region', cat='ice', lat=84.0, lon=40.0,
     epi='kanon', conf='Tinggi', label_only=True,
     pos='Latitude +90 [Kanon]; ice cap di ATAS LAUT [Kanon — PF §5.0].',
     canon='Established', status='Active', access='Remote', hemi='Aëris', scar='Unaffected', climate='Polar', hazards=['Climate'], region='Hemisfer Aëris — kutub utara', parent='Tâmtu',
     strategic='Massa es kutub = beban yang meredam True Polar Wander — komponen aktif dalam nasib orientasi planet, bukan dekorasi.',
     notes='Endonim Elvari/Tehari/Vayuri [Terbuka].', url=None),
dict(id='lobus', name='Porsi Lintas-Sutura', aka='BELUM BERNAMA — nol entri Atlas', type='Blank Spot', cat='blank', lat=8.0, lon=-102.0,
     epi='kanon', conf='Tinggi', label_only=True,
     pos='Kanon CI #110 / Change Log #6: porsi lintas-sutura superbenua ≈7,6% dari anggaran darat Aëris; koridor lon −159..−30. Bentuk = rekonstruksi.',
     canon='—', status='—', hemi='Aëris (litosfer)', region='Sisi Aëris koridor las — secara fisik bagian superbenua',
     strategic='Daratan terbesar yang belum punya satu entri pun di vault: litosfer Aëris (0,86–0,88 g, material basah) yang menyatu dengan Ferria lewat Pegunungan Sutura. Tujuan akhir satu-satunya jalur darat lintas-hemisfer.',
     notes='BLANK SPOT terbesar di peta. Siapa penghuninya, siapa yang mengklaimnya, dan kenapa manusia tidak di sana = pertanyaan terbuka.', url=None),
dict(id='mare_internum', name='Mare Internum', aka='label kerja — nama usulan', type='Body of Water', cat='water', lat=-11.0, lon=-44.0,
     epi='turunan', conf='Sedang', label_only=True, proposal=True,
     pos='Badan air ≈1,2% permukaan di selatan koridor Sutura, tersambung ke Sinus Adventus — kanon fisik sejak ketok Master Map v4 [Turunan]. Tafsir cekungan foreland (lempeng melentur di bawah beban sabuk pegunungan) dan nama = Inferensi AI. Merekonsiliasi "pita pesisir utara Ferria di barat teluk" (Hesperia) dengan koridor lintas-sutura.',
     canon='—', status='—', hemi='Rhykar', region='Antara Hesperia dan Pegunungan Sutura',
     strategic='Laut dalam bagi heartland Hesperia — jalur dagang internal Commonwealth, sekaligus parit antara manusia dan sabuk Scar.',
     notes='Badan airnya kanon fisik (ketok v4). Nama "Mare Internum", entri Atlas (kini Draft, 01 Okt 2026), dan relasi pesisir Hesperia belum diketok — dilacak di Development Backlog. Tanpa laut ini, koridor lon −159..−30 menghapus "pesisir utara" Hesperia secara harfiah.', url=None),
dict(id='emporys', name='Emporys', type='City-state (P&F)', cat='market', lat=18.55, lon=16.75,
     epi='turunan', conf='Sedang', proposal=True, faction='emporys',
     pos='Culmen Cicatricis (LPT): "Simpul netral tipe Emporys hidup dari status tak-terklaim ini" → di tanah pita Scar [Turunan]. Pulau di pita, di mulut teluk & awal rute Penyeberangan [Inferensi AI].',
     canon='Established (P&F)', status='Active', hemi='Aëris (litosfer pulau)', scar='Within Scar', region='Mulut Sinus Adventus — pulau pita Scar (usulan)',
     strategic='Persimpangan logistik yang terbentuk sebelum ada yang berniat membangun kota di sana; kredit bangsawan; peradilan dagang netral. Netralitas = properti geografis: tanah pita tidak bisa diklaim.',
     notes='Slot ledger "Simpul pasar netral Emporys" OPEN (Besar). Kandidat lama: gugus Nagû di persilangan koridor / pesisir tepi Scar — peta memilih yang kedua. Tekanan Foedera = tetangga terdekat.',
     url=None),
dict(id='perates', name='Pelabuhan Induk Peratēs', type='Usulan', cat='port', lat=7.78, lon=-16.04,
     epi='inferensi', conf='Rendah', proposal=True, faction='perates',
     pos='Kanon: "kota pelabuhan pertama yang menyadari mengendalikan jalur lebih menguntungkan dari menguasai lahan"; tanpa lahan subur, semua kalori diimpor. Ditempatkan di ujung semenanjung Culmen — terputus darat dari Hesperia, mengawasi sambungan Mare Internum ↔ mulut teluk [Inferensi AI — Rendah].',
     canon='—', status='Active', hemi='Rhykar', region='Ujung semenanjung Culmen (usulan)',
     strategic='Armada & hak eksklusif perdagangan pesisir yang diakui semua pihak karena biaya menentangnya lebih tinggi dari biaya membayarnya.',
     notes='Slot ledger "Pelabuhan induk Peratēs" OPEN. Kandidat ledger: Portus, gugus Nagû, atau kota pesisir Aëris.',
     url=None),
]

ANOMALIES = [
    dict(id='kantong_1', name='Kantong anomali massa #1 — Dies Ignis', lat=-1.25, lon=0.0, epi='kanon',
         note='"Salah satu titik [kantong anomali] = lokasi Dies Ignis" [Kanon — PF §4]. Titik litosfer Rhykar tertipis ke zona kontak.'),
    dict(id='kantong_2', name='Kantong anomali massa #2 — di bawah Fons Secundus', lat=-22.0, lon=-19.0, epi='inferensi',
         note='Rongga ringan Aëris di bawah benua Rhykar [Inferensi AI — Sedang, entri Fons Secundus]. Korelasi dengan Aurora Merah = Tension #21.'),
    dict(id='kantong_3', name='Kantong anomali massa #3 — di bawah Zona Ambang Ellumāt', lat=49.0, lon=144.0, epi='inferensi',
         note='Bongkahan litosfer Rhykar (Substansi I) di wilayah Aëris [Kanon — Canon Index #210, 29 Sep 2026]: sumber kontras yang dibaca Napûm Berteritori. Titik di peta mengikuti Zona Ambang = Inferensi AI (posisi persis → Tension #17). Tidak boleh ditulis sebagai titik kedatangan sebelum Tension #21 diputuskan.'),
]

# rute (daftar titik lat/lon); epi = status GARIS; topo = status topologi
ROUTES = [
    dict(id='penyeberangan', name='Rute Penyeberangan The Scar (bersejarah)', kind='historic', epi='inferensi', topo='kanon',
         note='Topologi T2 terkunci 4 Jul 2026: flank timur Sinus Adventus → bahu timur Culmen (rantai kantong stabil) → Zona Ambang Ellumāt → gerbang diplomatik Ring 2. Garis & jalur laut sesudah pita = Inferensi AI (Ellumāt di antipode, jadi ujung rute = pelayaran samudra ~120° bujur ke timur — Canon Index #87 diamandemen 29 Sep 2026).',
         pts=[(8.6, 14.6), (12.8, 16.2), (17.0, 17.6), (20.5, 19.0), (23.0, 24.0), (24.5, 31.0), (30.0, 40.0), (33.0, 52.0), (35.5, 66.0),
              (37.0, 80.0), (37.5, 95.0), (39.5, 108.0), (42.0, 120.0), (45.5, 131.0), (49.5, 139.0), (51.2, 143.5), (50.0, 151.0), (48.5, 160.0)]),
    dict(id='jalur_darat', name='Jalur darat barat (lintas Pegunungan Sutura)', kind='land', epi='inferensi', topo='kanon',
         note='Kanon (Change Log #6): satu-satunya jalur darat antar-hemisfer, menembus sabuk terdeformasi lewat teritori Birath. Lintasan & celah = Inferensi AI.',
         pts=[(-8.0, -38.0), (-14.0, -50.0), (-20.0, -60.0), (-25.5, -67.0), (-24.5, -72.5), (-19.0, -75.5), (-13.0, -77.0), (-7.0, -79.5), (-1.0, -82.0), (4.0, -84.0)]),
    dict(id='arc1', name='Rute Arc 1: Sharanya → Silva Nullius → Nundina', kind='story', epi='inferensi', topo='kanon',
         note='Topologi terkunci di entri Sharanya ("Titik nol rute Arc 1"). Jarak di peta: ≈270 km (2–3 minggu menghindari jalan besar) + ≈140 km (beberapa hari).',
         pts=[(-8.13, 5.05), (-8.9, 4.1), (-9.6, 3.1), (-9.9, 2.2), (-9.80, 1.19)]),
    dict(id='laut_utama', name='Usulan koridor angin & jalur laut utama', kind='sea', epi='inferensi', topo='terbuka',
         note='Tension #16 (Intentionally Deferred). Usulan: koridor Puncak — di puncak kurva (lon 0°) sabuk material sejajar ekuator sehingga angin gradient searah angin matahari → koridor kuat (Culmen: "Koridor angin kuat dekat busur ini menjelaskan konsentrasi lalu lintas maritim"). Gugus Nagû mengikuti koridor ini.',
         pts=[(12.5, 0.0), (19.0, 1.0), (24.5, -3.0), (27.5, -12.0), (29.0, -24.0), (27.0, -36.0), (24.0, -46.0), (21.0, -56.0)],
         pts2=[(24.5, -3.0), (26.5, 6.0), (29.5, 18.0), (33.5, 30.0), (37.0, 44.0), (38.5, 60.0), (39.0, 76.0), (38.5, 92.0)]),
]

FRONTS = [
    dict(id='front_florian', name='Front kampanye Florian (snapshot AS 1647)', epi='inferensi',
         note='Arah timur→barat & urutan Cassivalla → Tarvenna → … → Aventalia [Kanon]. Garis front = batas Provincia Cassivallae / Silva Nullius vs Tarvenna — Tension #19 (batas barat Foedera bergerak).',
         pts=[(-7.4, 2.4), (-10.8, 1.9), (-13.5, 2.6), (-16.0, 2.1), (-19.0, 2.8), (-22.0, 2.4)], arrow_to=(-15.0, -1.2)),
    dict(id='anabasim_fase1', name='Ekspansi Anabasim — Fase 1 (zona penyangga → frontier Rhykar)', epi='inferensi',
         note='Kanon: dari The Scar ke perbatasan hemisfer Rhykar, membentuk zona buffer yang defensible [Races — Birath].', pts=[(6.0, 31.0), (3.2, 27.0)], arrow_to=(1.5, 24.0)),
    dict(id='anabasim_fase3', name='Ekspansi Anabasim — fase lanjutan (sisi Aëris)', epi='inferensi',
         note='Kanon: "lalu mengarah ke sisi hemisfer Aëris" → Šadûmāt adalah daratan Aëris terdekat — tabrakan laten dengan Vayuri.', pts=[(7.0, 35.5), (10.0, 41.5)], arrow_to=(12.5, 45.5)),
]
